{% set name = "evfuncs" %}
{% set version = "0.3.5.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evfuncs-{{ version }}.tar.gz
  sha256: 3b73bc49f9e22c0e78eb00be32df0d03d88c72f90373657b36cb03c02a6bb75a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core >=3.2,<4
  run:
    - numpy >=1.18.1
    - python >=3.8
    - scipy >=1.2.0

test:
  imports:
    - evfuncs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/evfuncs/
  summary: Functions for working with files created by the EvTAF program and the evsonganaly GUI
  dev_url: https://github.com/NickleDave/evfuncs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
